Updated projects criteria
fmipython/PythonCourse2024 pull request #10
Opened 2024-12-26 07:18 UTC by lyubolp

2024-12-26 09:23 UTC, yalishanda42 requested changes
Супер, само може би бих отнел една точка от Git критерия, за да я добавя към type hint-овете

2024-12-30 11:07 UTC, alex-bronia requested changes

2024-12-30 11:07 UTC, alex-bronia commented on projects.md
> +   - Автоматично оценено, чрез `mypy`
Хм абе автоматичната оценка от `mypy` не трябва да я броим като пълни точки, понеже ако някъде няма type hints няма и да се оплаква за проблеми - `Any` е правилно винаги за type checker-a

2024-12-30 11:09 UTC, yalishanda42 commented on projects.md
> +   - Автоматично оценено, чрез `mypy`
(смесих малко гитхъб профилите, сори)

2024-12-30 11:10 UTC, yalishanda42 commented on projects.md
> +   - Автоматично оценено, чрез `mypy`
т.е. това което предлагам е комбинация ръчна проверка дали навсякъде, където има смисъл, има написани хинтове + автоматична проверка дали са верни/спазени от `mypy` (понеже то ще провери само там, където има)

2025-01-02 16:21 UTC, Bladwark approved these changes
Аз съм доволен от критериите

2025-01-02 21:22 UTC, yalishanda42 approved these changes

2025-01-02 21:23 UTC, alex-bronia approved these changes

2025-01-09 19:25 UTC, merged